"""Hidden role and skill taxonomy for opportunity-to-course matching.

Swelist often exposes only a title, category, and location.  These mappings
turn common title variants into a richer internal skill profile without
claiming that the employer explicitly listed those requirements.
"""

from __future__ import annotations


EXTRA_ROLE_SKILLS: dict[str, set[str]] = {
    "ai": {"nlp", "computer vision", "prompt engineering"},
    "machine-learning": {
        "computer vision",
        "nlp",
        "data visualization",
    },
    "data": {"data modeling", "cloud", "databases"},
    "security": {"siem", "cryptography", "cloud"},
    "devops": {"networking", "monitoring", "automation"},
    "cloud": {"terraform", "ci/cd", "cloud architecture"},
    "mobile": {"kotlin", "software testing", "ui"},
    "frontend": {"react", "ui", "ux", "accessibility"},
    "fullstack": {"typescript", "software testing", "docker"},
    "backend": {"java", "microservices", "software testing"},
    "software": {"programming", "problem solving"},
    "qa": {
        "software testing",
        "test automation",
        "programming",
        "ci/cd",
        "git",
        "rest api",
    },
    "database": {
        "sql",
        "databases",
        "data modeling",
        "etl",
        "linux",
        "cloud",
    },
    "embedded": {
        "c++",
        "embedded systems",
        "linux",
        "networking",
        "git",
        "data structures",
    },
    "product": {
        "product management",
        "business analysis",
        "project management",
        "communication",
        "data visualization",
        "sql",
    },
    "design": {
        "ux",
        "ui",
        "prototyping",
        "accessibility",
        "web",
        "communication",
    },
    "blockchain": {
        "programming",
        "distributed systems",
        "cryptography",
        "databases",
        "git",
    },
    "erp": {
        "business analysis",
        "sql",
        "data modeling",
        "project management",
        "cloud",
    },
    "business": {"business analysis"},
}


# Specific patterns are evaluated before the existing generic
# "developer/engineer/software" fallbacks.
EXTRA_ROLE_PATTERNS: list[tuple[str, tuple[str, ...]]] = [
    (
        "ai",
        (
            "ai engineer",
            "ai developer",
            "artificial intelligence",
            "generative ai",
            "gen ai",
            "llm",
            "large language model",
            "nlp",
            "natural language",
            "prompt engineer",
            "conversational ai",
        ),
    ),
    (
        "machine-learning",
        (
            "machine learning",
            "ml engineer",
            "data scientist",
            "computer vision",
            "deep learning",
            "applied scientist",
            "research scientist",
            "modeling scientist",
        ),
    ),
    (
        "data",
        (
            "data engineer",
            "data analyst",
            "analytics engineer",
            "data platform",
            "data warehouse",
            "business intelligence",
            "bi engineer",
            "bi developer",
            "insights analyst",
            "reporting analyst",
            "quantitative analyst",
        ),
    ),
    (
        "security",
        (
            "security",
            "cyber",
            "penetration",
            "soc analyst",
            "threat",
            "incident response",
            "digital forensics",
            "identity access",
            "application security",
            "appsec",
            "devsecops",
            "governance risk compliance",
            "grc analyst",
        ),
    ),
    (
        "devops",
        (
            "devops",
            "site reliability",
            "reliability engineer",
            "sre",
            "platform engineer",
            "infrastructure engineer",
            "build engineer",
            "release engineer",
            "deployment engineer",
            "production engineer",
        ),
    ),
    (
        "cloud",
        (
            "cloud",
            "solutions architect",
            "solution architect",
            "cloud architect",
            "cloud consultant",
            "cloud operations",
        ),
    ),
    (
        "mobile",
        (
            "mobile",
            "flutter",
            "ios",
            "android",
            "swift",
            "swiftui",
            "kotlin",
            "react native",
        ),
    ),
    (
        "frontend",
        (
            "front end",
            "front-end",
            "frontend",
            "react",
            "angular",
            "vue",
            "web developer",
            "web engineer",
            "ui engineer",
            "design system engineer",
        ),
    ),
    (
        "fullstack",
        ("full stack", "full-stack", "fullstack", "product engineer"),
    ),
    (
        "backend",
        (
            "back end",
            "back-end",
            "backend",
            "api engineer",
            "server engineer",
            "microservices engineer",
            "integration engineer",
            "middleware engineer",
        ),
    ),
    (
        "qa",
        (
            "quality assurance",
            "quality engineer",
            "qa engineer",
            "qa analyst",
            "test engineer",
            "test automation",
            "automation engineer",
            "software tester",
            "sdet",
            "verification engineer",
        ),
    ),
    (
        "database",
        (
            "database administrator",
            "database engineer",
            "database developer",
            "dba",
            "sql developer",
            "data modeler",
        ),
    ),
    (
        "embedded",
        (
            "embedded",
            "firmware",
            "internet of things",
            "iot engineer",
            "robotics engineer",
            "hardware software",
        ),
    ),
    (
        "networking",
        (
            "network engineer",
            "network operations",
            "network administrator",
            "noc engineer",
            "telecommunications",
        ),
    ),
    (
        "it-support",
        (
            "technical support",
            "it support",
            "helpdesk",
            "service desk",
            "desktop support",
            "systems administrator",
            "system administrator",
            "application support",
            "support engineer",
            "technical operations",
        ),
    ),
    (
        "product",
        (
            "product manager",
            "product owner",
            "product analyst",
            "product operations",
            "program manager",
            "technical program",
        ),
    ),
    (
        "design",
        (
            "ux designer",
            "ui designer",
            "product designer",
            "user experience",
            "interaction designer",
        ),
    ),
    (
        "blockchain",
        ("blockchain", "web3", "smart contract", "distributed ledger"),
    ),
    (
        "erp",
        (
            "erp",
            "sap consultant",
            "sap functional",
            "sap technical",
            "sap developer",
            "salesforce",
            "crm developer",
            "business systems",
            "enterprise applications",
        ),
    ),
    (
        "business",
        (
            "business analyst",
            "project manager",
            "operations analyst",
            "strategy analyst",
            "management consultant",
            "technology consultant",
            "implementation consultant",
            "functional consultant",
            "process analyst",
            "store operations",
        ),
    ),
]


EXTRA_SKILL_ALIASES: dict[str, tuple[str, ...]] = {
    "programming": ("programming", "software development", "coding"),
    "problem solving": ("problem solving", "analytical thinking"),
    "communication": ("communication", "stakeholder management"),
    "c++": ("c++", "cpp"),
    "react": ("react", "next.js", "nextjs"),
    "angular": ("angular",),
    "vue": ("vue", "vue.js"),
    "node.js": ("node.js", "nodejs"),
    "spring": ("spring", "spring boot"),
    "django": ("django",),
    "flask": ("flask", "fastapi"),
    "kotlin": ("kotlin", "android"),
    "data modeling": (
        "data modeling",
        "data modelling",
        "data warehouse",
        "star schema",
    ),
    "ci/cd": (
        "ci/cd",
        "continuous integration",
        "continuous delivery",
        "github actions",
        "azure devops",
    ),
    "terraform": ("terraform", "infrastructure as code", "iac"),
    "nlp": ("nlp", "natural language processing"),
    "computer vision": ("computer vision", "image processing", "opencv"),
    "siem": ("siem", "splunk", "sentinel"),
    "cryptography": ("cryptography", "encryption"),
    "test automation": (
        "test automation",
        "selenium",
        "cypress",
        "playwright",
        "sdet",
    ),
    "microservices": ("microservice", "distributed services"),
    "ui": ("user interface", "ui development", "design system"),
    "ux": ("user experience", "ux"),
    "accessibility": ("accessibility", "wcag"),
    "product management": ("product management", "product owner"),
    "business analysis": (
        "business analysis",
        "requirements analysis",
        "process analysis",
    ),
    "spreadsheets": ("excel", "spreadsheets", "google sheets"),
    "embedded systems": ("embedded", "firmware", "iot"),
    "distributed systems": ("distributed systems", "blockchain", "web3"),
    "prototyping": ("prototyping", "figma"),
    "monitoring": ("monitoring", "observability", "grafana", "prometheus"),
    "automation": ("automation", "scripting"),
    "cloud architecture": ("cloud architecture", "solutions architecture"),
    "prompt engineering": ("prompt engineering", "prompt design"),
}


SKILL_IMPLICATIONS: dict[str, set[str]] = {
    "python": {"programming"},
    "java": {"programming"},
    "c#": {"programming"},
    "c++": {"programming"},
    "javascript": {"programming", "web"},
    "typescript": {"javascript", "programming", "web"},
    "react": {"javascript", "typescript", "web", "ui"},
    "angular": {"typescript", "web", "ui"},
    "vue": {"javascript", "web", "ui"},
    "node.js": {"javascript", "programming", "rest api"},
    "spring": {"java", "rest api", "microservices", "databases"},
    "django": {"python", "rest api", "databases", "web"},
    "flask": {"python", "rest api", "web"},
    "flutter": {"programming", "mobile", "ui"},
    "swift": {"programming", "mobile"},
    "kotlin": {"programming", "mobile"},
    "sql": {"databases"},
    "data modeling": {"databases"},
    "docker": {"automation"},
    "kubernetes": {"docker", "cloud", "automation"},
    "ci/cd": {"automation", "software testing"},
    "terraform": {"cloud", "automation"},
    "aws": {"cloud"},
    "azure": {"cloud"},
    "pytorch": {"python", "machine learning"},
    "llm": {"machine learning"},
    "rag": {"llm", "python"},
    "nlp": {"machine learning", "python"},
    "computer vision": {"machine learning", "python"},
    "siem": {"cybersecurity"},
    "cryptography": {"cybersecurity"},
    "etl": {"python", "sql", "data modeling"},
    "algorithms": {"problem solving", "programming"},
    "data structures": {"algorithms", "programming"},
    "test automation": {"software testing", "programming"},
    "microservices": {"rest api", "distributed systems"},
    "embedded systems": {"c++", "linux"},
}


TITLE_SKILL_HINTS: list[tuple[tuple[str, ...], set[str]]] = [
    (
        ("computer vision", "image processing", "visual perception"),
        {"computer vision", "machine learning", "python", "pytorch"},
    ),
    (
        ("nlp", "natural language", "language model", "conversational ai"),
        {"nlp", "machine learning", "python", "llm"},
    ),
    (
        ("generative ai", "gen ai", "llm", "prompt engineer"),
        {"llm", "rag", "python", "machine learning", "prompt engineering"},
    ),
    (
        ("data engineer", "analytics engineer", "data platform"),
        {"python", "sql", "etl", "data modeling", "cloud"},
    ),
    (
        ("data analyst", "business intelligence", "insights analyst"),
        {"sql", "statistics", "data visualization", "spreadsheets"},
    ),
    (
        ("backend", "back-end", "api engineer", "microservices"),
        {"rest api", "databases", "microservices", "docker", "linux"},
    ),
    (
        ("frontend", "front-end", "ui engineer", "web developer"),
        {"javascript", "typescript", "web", "ui", "accessibility"},
    ),
    (
        ("full stack", "full-stack", "fullstack"),
        {"javascript", "typescript", "rest api", "databases", "web"},
    ),
    (
        ("quality", "qa ", "test engineer", "sdet", "automation engineer"),
        {"software testing", "test automation", "ci/cd", "git"},
    ),
    (
        ("devops", "platform engineer", "site reliability", "sre"),
        {"docker", "kubernetes", "ci/cd", "terraform", "linux", "cloud"},
    ),
    (
        ("cloud", "solutions architect", "solution architect"),
        {"cloud", "aws", "azure", "networking", "docker"},
    ),
    (
        ("security", "cyber", "soc analyst", "penetration", "appsec"),
        {"cybersecurity", "network security", "linux", "python", "siem"},
    ),
    (
        ("ios", "swift", "android", "kotlin", "flutter", "mobile"),
        {"mobile", "flutter", "swift", "kotlin", "rest api"},
    ),
    (
        ("embedded", "firmware", "iot", "robotics"),
        {"embedded systems", "c++", "linux", "networking"},
    ),
    (
        ("database", "dba", "sql developer", "data modeler"),
        {"sql", "databases", "data modeling", "linux", "cloud"},
    ),
    (
        ("product manager", "product owner", "product analyst"),
        {
            "product management",
            "business analysis",
            "project management",
            "data visualization",
        },
    ),
    (
        ("business analyst", "consultant", "operations analyst"),
        {
            "business analysis",
            "project management",
            "sql",
            "data visualization",
            "communication",
        },
    ),
]


ROLE_COURSE_AFFINITY: dict[str, tuple[str, ...]] = {
    "ai": ("ibm-generative-ai", "ibm-ai-developer"),
    "machine-learning": ("ibm-machine-learning", "google-advanced-data"),
    "data": ("google-data-analytics", "google-business-intelligence"),
    "security": ("google-cybersecurity", "microsoft-cybersecurity"),
    "devops": ("ibm-devops", "microsoft-devops"),
    "cloud": ("aws-solutions-architect", "aws-cloud-support"),
    "mobile": ("meta-ios",),
    "frontend": ("microsoft-fullstack",),
    "fullstack": ("microsoft-fullstack", "meta-backend"),
    "backend": ("meta-backend", "microsoft-fullstack"),
    "software": ("boulder-algorithms", "deeplearning-generative-swd"),
    "qa": ("deeplearning-generative-swd", "ibm-devops"),
    "database": ("google-business-intelligence", "meta-backend"),
    "embedded": ("boulder-algorithms", "google-it-automation"),
    "networking": ("akamai-networking",),
    "it-support": ("google-it-automation", "aws-cloud-support"),
    "product": ("google-business-intelligence", "google-data-analytics"),
    "design": ("microsoft-fullstack", "meta-ios"),
    "blockchain": ("boulder-algorithms", "meta-backend"),
    "erp": ("google-business-intelligence", "google-data-analytics"),
    "business": ("google-business-intelligence", "google-data-analytics"),
    "general": ("google-it-automation", "boulder-algorithms"),
}
